name: Build and Code scanning..

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '22 18 * * 3'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [12.x]
        os: [ubuntu-latest]
        language: [javascript, typescript]

    steps:
      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Downloads Checkouts...
        uses: actions/checkout@v1
      - name: Create Firebase Configuration for Neon K.I.D
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          echo $FIREBASE_CONFIG > src/components/Server/firebase/config.json
      - name: Initialize CodeQL..
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
      - name: Portpolio Build...
        run: |
          npm install
          npm run build:css
          npm run build
