name: Build

on: 
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [8.x]
        os: [ubuntu-latest]

    steps:
      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Downloads Checkouts...
        uses: actions/checkout@v1
      - name: Portpolio Build...  
        run: |
          npm install
          cp -rf config/webpack.config.prod.js node_modules/react-scripts/config/webpack.config.prod.js
          npm run build-css
          npm run build --if-present
        