name: Portpolio-react Build

on: [ pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [10.x]
        os: [ubuntu-latest]

    steps:
      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Downloads Checkouts...
        uses: actions/checkout@v1
      - name: Portpolio Build...  
        run: |
          npm install
          npm run build-css
          npm run build --if-present
        