name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [10.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Build SASS -> CSS
        run: |
          npm install
          npm run build:css
      - name: Deploy Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm -g install firebase-tools
          firebase deploy --token $FIREBASE_TOKEN --non-interactive
